drop database if exists `GDP_INFO`;

/*CREATE THE DATABASE */
create database `GDP_INFO`;
use `GDP_INFO`;


CREATE TABLE GDP_DATA 
(COUNTRY VARCHAR (200),
COUNTRYCODE VARCHAR (200),
YEAR_  DATETIME,
GDP_Value float
);

LOAD DATA LOCAL INFILE "C:\Users\User\Desktop\2022\POWER BI WITH SQL and build an AUTOMATED DATA\data\gdp_csv.csv" INTO TABLE GDP_INFO.GDP_Data
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\n'
;
SELECT * FROM GDP_DATA